import {test} from 'node:test';
import assert from 'node:assert/strict';
import {reservation,validate,schemas} from '../src/validation.js';
import {createDatabase,pgTypes} from '../src/db.js';
import {smtpConfiguration,buildMessage} from '../src/notifications.js';
const valid={name:'Test',email:'test@example.invalid',phone:'+2250102030405',arrival:'2099-10-10',departure:'2099-10-12',adults:1,children:0,room_type_id:null,message:'',consent:true};
test('validation des dates, quantités et consentement',()=>{for(const change of [{departure:'2099-10-09'},{arrival:'2020-01-01'},{arrival:'2099-02-30'},{adults:0},{adults:1.5},{children:-1},{consent:false}])assert.throws(()=>validate(reservation,{...valid,...change}));assert.equal(validate(reservation,valid).adults,1);});
test('PostgreSQL : dates calendaires et entiers sans perte de précision',()=>{assert.equal(pgTypes.getTypeParser(1082)('2099-10-10'),'2099-10-10');assert.equal(pgTypes.getTypeParser(20)('120000'),120000);assert.equal(pgTypes.getTypeParser(20)('9007199254740993'),'9007199254740993');});
test('les requêtes ne reçoivent jamais un RETURNING id implicite',async()=>{let statement;const db=createDatabase({query:async sql=>{statement=sql;return {command:'INSERT',rows:[],rowCount:1};}});const sql='INSERT INTO room_type_media(room_type_id,media_id) VALUES ($1,$2)';await db.execute(sql,[1,2]);assert.equal(statement,sql);});
test('SMTP : aucune adresse de réception inventée',()=>{const config=smtpConfiguration({SMTP_HOST:'smtp.example.invalid'});assert.equal(config.configured,false);assert.deepEqual(config.missing,['SMTP_FROM','NOTIFICATION_EMAIL']);});
test('un contact ne reçoit jamais une confirmation de séjour',async()=>{const result=await buildMessage({request_type:'contacts',request_id:1,kind:'confirmation'},{query:async()=>[[{id:1,status:'confirmed',email:'contact@example.invalid'}]]},{});assert.equal(result,null);});
test('les conditions facultatives acceptent NULL depuis PostgreSQL',()=>{const r=validate(schemas.room_types,{slug:'test',name:'Test',description:'Test',capacity:null,price_fcfa:null,conditions_text:null,status:'draft',validated:false,is_demo:true});assert.equal(r.conditions_text,'');});
