import {test,before} from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import bcrypt from 'bcrypt';
import {createApp} from '../src/app.js';
import {reservation,validate} from '../src/validation.js';
process.env.SESSION_SECRET='test-only-secret-not-for-production-123456789';
const valid={name:'Test Client',email:'test@example.org',phone:'+225 0102030405',arrival:'2099-10-10',departure:'2099-10-12',adults:1,children:0,room_type_id:null,message:'Test',consent:true};
let passwordHash;
before(async()=>{passwordHash=await bcrypt.hash('a-strong-test-password',4);});
function fakeDB(){const state={requests:[],room:null};const database={state,async execute(sql,args){if(sql.startsWith('SELECT id,password_hash'))return [[{id:1,password_hash:passwordHash}]];if(sql.startsWith('INSERT INTO reservation_requests')){state.requests.push({id:1,values:args,notification_status:'pending'});return [{insertId:1}];}if(sql.includes('SET notification_status')){state.requests[0].notification_status=args[0];return [{affectedRows:1}];}if(sql.startsWith('UPDATE room_types')){state.room=args;return [{affectedRows:1}];}if(sql.startsWith('SELECT capacity'))return [[{capacity:2}]];return [{affectedRows:1}];},async query(){return [[]];},async getConnection(){return {...database,beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release:()=>{}};}};return database;}
test('validation : dates inversées, passées ou impossibles, quantités et consentement',()=>{for(const change of [{departure:'2099-10-09'},{arrival:'2020-01-01'},{arrival:'2099-02-30'},{adults:0},{adults:1.5},{children:-1},{consent:false}])assert.throws(()=>validate(reservation,{...valid,...change}));assert.equal(validate(reservation,valid).adults,1);});
test('API : enregistrement conservé malgré un échec SMTP',async()=>{const database=fakeDB();const app=createApp({database,transport:{sendMail:async()=>{throw Error('SMTP unavailable');}}});const res=await request(app).post('/api/reservations').send(valid);assert.equal(res.status,201);assert.equal(database.state.requests.length,1);assert.equal(database.state.requests[0].notification_status,'failed');assert.match(res.body.message,/confirmer la disponibilité/);});
test('API : dates invalides rejetées avant toute insertion',async()=>{const database=fakeDB();const res=await request(createApp({database})).post('/api/reservations').send({...valid,departure:valid.arrival});assert.equal(res.status,422);assert.ok(res.body.fields.departure);assert.equal(database.state.requests.length,0);});
test('API : capacité vérifiée côté serveur',async()=>{const database=fakeDB();const res=await request(createApp({database})).post('/api/reservations').send({...valid,room_type_id:1,adults:3});assert.equal(res.status,422);assert.equal(database.state.requests.length,0);});
test('admin : accès interdit sans connexion',async()=>{const app=createApp({database:fakeDB()});assert.equal((await request(app).get('/api/admin/room_types')).status,401);assert.equal((await request(app).put('/api/admin/room_types/1').send({})).status,401);});
test('admin : authentification, CSRF et modification de chambre',async()=>{const database=fakeDB(),agent=request.agent(createApp({database}));const session=await agent.get('/api/auth/session');assert.equal((await agent.post('/api/auth/login').send({email:'admin@example.org',password:'a-strong-test-password'})).status,403);const login=await agent.post('/api/auth/login').set('X-CSRF-Token',session.body.csrf).send({email:'admin@example.org',password:'a-strong-test-password'});assert.equal(login.status,200);const body={slug:'chambre-test',name:'Chambre test',description:'Description vérifiée',capacity:2,price_fcfa:null,status:'draft',validated:false,is_demo:true,amenity_ids:[],media_ids:[]};assert.equal((await agent.put('/api/admin/room_types/1').send(body)).status,403);const saved=await agent.put('/api/admin/room_types/1').set('X-CSRF-Token',login.body.csrf).send(body);assert.equal(saved.status,200);assert.ok(database.state.room.includes('Chambre test'));const publish=await agent.put('/api/admin/room_types/1').set('X-CSRF-Token',login.body.csrf).send({...body,status:'published'});assert.equal(publish.status,422);await agent.post('/api/auth/logout').set('X-CSRF-Token',login.body.csrf);assert.equal((await agent.get('/api/admin/room_types')).status,401);});
