INSERT INTO room_types (slug,name,description,capacity,status,is_demo) VALUES ('chambre-exemple','Chambre — exemple de présentation','Photographie fournie. Nom de catégorie, capacité et équipements à confirmer par l’hôtel.',2,'draft',TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO page_contents (slug,title,body,is_demo) VALUES ('hotel','Le charme de Bassam, la douceur de l’océan','Découvrez le Wharf Hôtel à Grand-Bassam. Les informations détaillées sur l’établissement seront complétées après validation par l’hôtel.',TRUE),('restaurant','Une pause à votre rythme','Présentation du restaurant à confirmer. Contactez l’hôtel pour connaître les menus et les horaires.',TRUE),('piscine-plage','Entre piscine et océan','Les conditions d’accès, les équipements et les horaires seront précisés par l’hôtel.',TRUE),('evenements','Des moments à partager','Mariages, réceptions ou séminaires : présentez votre projet. Les espaces et leurs capacités restent à confirmer.',TRUE),('mentions-legales','Mentions légales','À compléter avant publication : identité et forme juridique de l’exploitant, immatriculation, adresse du siège, directeur de publication et hébergeur.',TRUE),('confidentialite','Politique de confidentialité','Projet à valider avant publication. Les informations de vos formulaires sont destinées au traitement de votre demande par l’hôtel. À compléter : responsable du traitement, base légale, durée de conservation, destinataires, modalités d’exercice des droits et contact.',TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO hotel_settings (setting_key,value) VALUES ('address','Boulevard Treich-Laplène, Quartier France / Plage d’Assoyam'),('phone','+225 27 21 30 15 33'),('email','lewharfhotel@gmail.com'),('facebook','https://www.facebook.com/Wharfhotelbassam/'),('maps','https://www.google.com/maps?q=5.1949396,-3.7355957') ON CONFLICT (setting_key) DO NOTHING;
INSERT INTO media (url,alt,category,is_demo) SELECT '/photos/27.jpg','Vue de la piscine et des jardins','Hôtel',TRUE WHERE NOT EXISTS (SELECT 1 FROM media WHERE url='/photos/27.jpg');
INSERT INTO media (url,alt,category,is_demo) SELECT '/photos/26.jpg','Intérieur d’une chambre photographiée','Chambres',TRUE WHERE NOT EXISTS (SELECT 1 FROM media WHERE url='/photos/26.jpg');
INSERT INTO media (url,alt,category,is_demo) SELECT '/photos/103.jpg','Piscine extérieure','Piscine',TRUE WHERE NOT EXISTS (SELECT 1 FROM media WHERE url='/photos/103.jpg');
INSERT INTO media (url,alt,category,is_demo) SELECT '/photos/15.jpg','Espace extérieur près du bord de mer','Restaurant',TRUE WHERE NOT EXISTS (SELECT 1 FROM media WHERE url='/photos/15.jpg');
INSERT INTO media (url,alt,category,is_demo) SELECT '/photos/81.jpg','Vue de l’océan au coucher du soleil','Plage',TRUE WHERE NOT EXISTS (SELECT 1 FROM media WHERE url='/photos/81.jpg');
INSERT INTO room_type_media SELECT r.id,m.id FROM room_types r JOIN media m ON m.url='/photos/26.jpg' WHERE r.slug='chambre-exemple' ON CONFLICT (room_type_id, media_id) DO NOTHING;

