import React,{useEffect,useState} from 'react';
import {api} from './api';
const labels={pending:'En attente',processing:'En cours',confirmed:'Confirmée',declined:'Refusée',cancelled:'Annulée'};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function ReservationBrowser({onOpen,refreshToken}){
 const [q,setQ]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[day,setDay]=useState(''),[month,setMonth]=useState(iso(new Date()).slice(0,7)),[rows,setRows]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(async()=>{try{const data=await api('/admin/reservations?'+new URLSearchParams({q,status,from,to}));if(active){setRows(data);setError('');}}catch(e){if(active)setError(e.message);}finally{if(active)setLoading(false);}},250);return()=>{active=false;clearTimeout(timer);};},[q,status,from,to,refreshToken]);
 const [year,m]=month.split('-').map(Number),first=new Date(year,m-1,1),count=new Date(year,m,0).getDate(),offset=(first.getDay()+6)%7;
 const visible=day?rows.filter(r=>r.arrival<=day&&r.departure>day):rows;
 return <section className="reservation-browser">
  <div className="reservation-filters"><label>Rechercher<input type="search" placeholder="Nom, e-mail, téléphone ou numéro" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Statut<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Séjour à partir du<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Jusqu’au<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setQ('');setStatus('');setFrom('');setTo('');setDay('');}}>Réinitialiser</button></div>
  <div className="reservation-calendar"><label>Mois du calendrier<input type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setDay('');}}}/></label><p>Choisissez un jour pour afficher les séjours présents cette nuit-là. Le jour de départ est exclu. Les couleurs indiquent les statuts.</p><div className="calendar-grid">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:offset},(_,i)=><span key={'empty'+i}/>)}{Array.from({length:count},(_,i)=>{const date=iso(new Date(year,m-1,i+1)),matches=rows.filter(r=>r.arrival<=date&&r.departure>date);return <button disabled={loading||!!error} key={date} className={day===date?'selected':''} aria-pressed={day===date} aria-label={date+', '+matches.length+' réservation(s)'} onClick={()=>setDay(day===date?'':date)}><b>{i+1}</b><small>{matches.length||'—'}</small><span className="calendar-dots">{Object.keys(labels).filter(s=>matches.some(r=>r.status===s)).map(s=><i title={labels[s]} className={'status-'+s} key={s}/>)}</span></button>;})}</div><div className="calendar-legend">{Object.entries(labels).map(([s,l])=><span key={s}><i className={'status-'+s}/>{l}</span>)}</div></div>
  {day&&<button className="secondary" onClick={()=>setDay('')}>Retirer le filtre du {day}</button>}
  {error?<p role="alert" className="field-error">{error}</p>:loading?<p role="status">Recherche des réservations…</p>:<><p role="status">{visible.length} réservation(s){day?' pour le '+day:''}</p><div className="admin-list">{visible.map(r=><article key={r.id}><div><h2>#{r.id} · {r.name}</h2><p>{r.email} · {labels[r.status]}</p><p>Du {r.arrival} au {r.departure} · {r.adults} adulte(s), {r.children} enfant(s)</p></div><button onClick={()=>onOpen({...r})}>Consulter</button></article>)}{!visible.length&&<p>Aucune réservation ne correspond aux filtres.</p>}</div></>}
 </section>;
}
